# Generated by Django 3.1.5 on 2021-10-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211027_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(default='', max_length=10)),
                ('phone', models.IntegerField(default=0)),
                ('desc', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
