# Generated by Django 3.1.5 on 2021-10-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211028_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
