# Generated by Django 3.1.5 on 2021-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211028_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=13),
        ),
    ]
